name: "Build"
on:
  push:
    branches:
      - main
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - run: nix flake check
      - uses: cachix/cachix-action@v12
        with:
          name: gametaro-neovim-flake
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Pushing flake inputs
        run: |
          nix flake archive --json \
            | jq -r '.path,(.inputs|to_entries[].value.path)' \
            | cachix push gametaro-neovim-flake
      - name: Pushing runtime closure
        run: |
          nix build --json \
            | jq -r '.[].outputs | to_entries[].value' \
            | cachix push gametaro-neovim-flake
      - name: Pushing shell environment
        run: |
          nix develop --profile dev -c true
          cachix push gametaro-neovim-flake dev
